import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import Head from "next/head";
import "./css/globals.css";
import "./css/style.css";
import "./css/L.Icon.Pulse.css";
import "ol/ol.css"; // OpenLayersのデフォルトスタイルをインポート

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const mPlusRounded1c = Geist({
  variable: "--font-m-plus-rounded-1c",
  subsets: ["latin"],
  weight: ["400", "700"],
});

// viewport を metadata から分離して別の export にする
export const viewport = {
  width: "device-width",
  initialScale: 1,
};

// metadata から viewport の設定を削除
export const metadata: Metadata = {
  title: "ねいちず-NatureMaps-",
  description: "Generated by create next app",
  robots: "noindex,nofollow",
  icons: {
    icon: "/img/logo.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ja"
      className={`${geistSans.variable} ${geistMono.variable} ${mPlusRounded1c.variable}`}
    >
      <Head>
        {/* faviconの読み込み */}
        <link rel="icon" href="/img/logo.ico" />
        {/* OpenLayers用のスタイルシート */}
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.5.0/css/ol.css"
          type="text/css"
        />
      </Head>
      <body className="antialiased">
        {children}
        <Script
          src="https://code.jquery.com/jquery-2.2.4.min.js"
          integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
          crossOrigin="anonymous"
        />
      </body>
    </html>
  );
}
