import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import "./css/style.css";
import "./css/L.Icon.Pulse.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const mPlusRounded1c = Geist({
  variable: "--font-m-plus-rounded-1c",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "ねいちず-NatureMaps-",
  description: "Generated by create next app",
  robots: "noindex,nofollow",
  viewport: "width=device-width, initial-scale=1.0",
  icons: {
    icon: "/img/mountain.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ja"
      className={`${geistSans.variable} ${geistMono.variable} ${mPlusRounded1c.variable}`}
    >
      {/* faviconの読み込み */}
      <link rel="icon" href="img/mountain.ico" />
      {/* fontの読み込み */}
      {/* <link
  href="https://fonts.googleapis.com/css2?family=YourFont&display=optional"
  rel="stylesheet"
/> */}
      <body className="antialiased">
        {children}
        <Script
          src="https://code.jquery.com/jquery-2.2.4.min.js"
          integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
          crossOrigin="anonymous"
        />
      </body>
    </html>
  );
}
